# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-29 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
        ('blog', '0002_auto_20150527_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('photo', models.ImageField(upload_to='coachs')),
                ('Club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league_manager.Club')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('menuIcon', models.CharField(choices=[('torso', 'torso'), ('torsos-all', 'torsos-all'), ('home', 'home')], default='torso', max_length=50)),
            ],
            options={
                'ordering': ('_order',),
            },
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='GeneralPost',
            fields=[
                ('blogpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.BlogPost')),
                ('sub_title', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
            bases=('blog.blogpost',),
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Roster_Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max', models.PositiveSmallIntegerField()),
                ('position', models.CharField(max_length=30)),
                ('cost', models.PositiveSmallIntegerField()),
                ('M', models.PositiveSmallIntegerField()),
                ('Ag', models.PositiveSmallIntegerField()),
                ('F', models.PositiveSmallIntegerField()),
                ('Ar', models.PositiveSmallIntegerField()),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_manager.Ref_Roster')),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('family', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_manager.Coach')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_manager.League')),
                ('ref_roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_manager.Ref_Roster')),
            ],
        ),
        migrations.CreateModel(
            name='Xp_Roll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Values', models.CharField(max_length=30)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_manager.Player')),
            ],
        ),
        migrations.AddField(
            model_name='ref_roster_line',
            name='skills',
            field=models.ManyToManyField(to='league_manager.Ref_Skills'),
        ),
        migrations.AddField(
            model_name='player',
            name='ref_roster_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_manager.Ref_Roster_Line'),
        ),
        migrations.AddField(
            model_name='player',
            name='skills',
            field=models.ManyToManyField(to='league_manager.Ref_Skills'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_manager.Team'),
        ),
    ]
