# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Roster_Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max', models.PositiveSmallIntegerField()),
                ('position', models.CharField(max_length=30)),
                ('cost', models.PositiveSmallIntegerField()),
                ('M', models.PositiveSmallIntegerField()),
                ('Ag', models.PositiveSmallIntegerField()),
                ('F', models.PositiveSmallIntegerField()),
                ('Ar', models.PositiveSmallIntegerField()),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_manager.Ref_Roster')),
            ],
        ),
        migrations.CreateModel(
            name='Ref_Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('family', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_manager.League')),
                ('ref_roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_manager.Ref_Roster')),
            ],
        ),
        migrations.CreateModel(
            name='Xp_Roll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Values', models.CharField(max_length=30)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_manager.Player')),
            ],
        ),
        migrations.AddField(
            model_name='ref_roster_line',
            name='skills',
            field=models.ManyToManyField(to='league_manager.Ref_Skills'),
        ),
        migrations.AddField(
            model_name='player',
            name='ref_roster_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_manager.Ref_Roster_Line'),
        ),
        migrations.AddField(
            model_name='player',
            name='skills',
            field=models.ManyToManyField(to='league_manager.Ref_Skills'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_manager.Team'),
        ),
    ]
