# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-16 08:02
from __future__ import unicode_literals

from django.db import migrations, models
from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_admin_user(apps, schema_editor):
     User = apps.get_registered_model('auth', 'User')
     admin = User(
         username='Bagouze',
         email='bertrand.begouin@gmail.com',
         password=make_password('ignakO75'),
         is_superuser=True,
         is_staff=True
     )
     admin.save()


class Migration(migrations.Migration):

    def create_super_user(apps, schema_editor):
        # We can't create_super_user the Person model directly as it may be a newer
        # version than this migration expects. We use the historical version.
        Person = apps.get_model("yourappname", "Person")
        for person in Person.objects.all():
            person.name = "%s %s" % (person.first_name, person.last_name)
            person.save()

    dependencies = [
        ('league_manager', '0001_initial'),
         ('auth', '0001_initial')
    ]

    operations = [
        migrations.RunPython(create_admin_user),
    ]
