# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-21 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_manager', '0004_auto_20160919_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='num',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
