# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-26 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_manager', '0005_player_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
