# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-02 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league_manager', '0008_auto_20161002_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerevolution',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='playerevolution',
            old_name='new_skill',
            new_name='skill',
        ),
    ]
