# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-17 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from league_manager.models.club import Club
from league_manager.models.league import League
from league_manager.models.starting_rules import StartingRules

def init_club_and_league(apps, schema_editor):

    new_club = Club(name = "Valdemor BBC")
    new_club.save()

    starting_rules = StartingRules(max_budget=1100,
                                   max_simple_skills = 3,
                                   max_double_skills=1)
    starting_rules.save()

    new_league = League(name = "saison 2016 - 2017",
                        Club = new_club,
                        starting_rules=starting_rules)
    new_league.save()

class Migration(migrations.Migration):

    dependencies = [
        ('league_manager', '0010_auto_20161017_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartingRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_budget', models.SmallIntegerField()),
                ('max_simple_skills', models.SmallIntegerField()),
                ('max_double_skills', models.SmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='starting_rules',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league_manager.StartingRules'),
        ),
        migrations.RunPython(init_club_and_league),
    ]
