# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-20 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league_manager', '0012_auto_20161017_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supporters', models.PositiveSmallIntegerField()),
                ('fame', models.PositiveSmallIntegerField()),
                ('winnings', models.PositiveSmallIntegerField()),
                ('fan_factor', models.SmallIntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Match_Report',
            new_name='MatchReport',
        ),
        migrations.RemoveField(
            model_name='team_report',
            name='match',
        ),
        migrations.RemoveField(
            model_name='team_report',
            name='team',
        ),
        migrations.AlterField(
            model_name='playerreport',
            name='team_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_manager.TeamReport'),
        ),
        migrations.DeleteModel(
            name='Team_Report',
        ),
        migrations.AddField(
            model_name='teamreport',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_reports', to='league_manager.MatchReport'),
        ),
        migrations.AddField(
            model_name='teamreport',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='league_manager.Team'),
        ),
    ]
