# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-21 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league_manager', '0013_auto_20161020_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchreport',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playerreport',
            name='team_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_report', to='league_manager.TeamReport'),
        ),
    ]
