# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-21 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league_manager', '0014_auto_20161021_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerreport',
            old_name='serious_casualty',
            new_name='injury_type',
        ),
    ]
