# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-21 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_manager', '0016_teamreport_other_casualties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerreport',
            name='earned_xp',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playerreport',
            name='injury_type',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playerreport',
            name='is_wounded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playerreport',
            name='nb_blocks',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerreport',
            name='nb_cas',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerreport',
            name='nb_foul',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerreport',
            name='nb_int',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerreport',
            name='nb_mvp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerreport',
            name='nb_pass',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerreport',
            name='nb_td',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
