# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-25 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_manager', '0017_auto_20161021_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchreport',
            name='date',
            field=models.DateField(null=True, verbose_name='Date de la rencontre'),
        ),
        migrations.AlterField(
            model_name='matchreport',
            name='weather',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
