# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-31 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_manager', '0020_teamreport_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerreport',
            name='nb_mvp',
        ),
        migrations.AddField(
            model_name='playerreport',
            name='mvp',
            field=models.BooleanField(default=False),
        ),
    ]
