# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-31 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_manager', '0021_auto_20161031_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='TV',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='ranking_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
