# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-31 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_manager', '0022_auto_20161031_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerupgrade',
            name='xp_roll',
        ),
        migrations.AlterField(
            model_name='player',
            name='need_upgrade',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_xp',
            field=models.SmallIntegerField(default=0),
        ),
    ]
