# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-03 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_manager', '0023_auto_20161031_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bonus_point',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
