# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-03 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_manager', '0024_team_bonus_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_journeyman',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerupgrade',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='miss_next_game',
            field=models.BooleanField(default=False),
        ),
    ]
