# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-04 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_manager', '0025_auto_20161103_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Ag',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='Ar',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='F',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='M',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='skills',
            field=models.ManyToManyField(to='league_manager.Ref_Skills'),
        ),
    ]
