# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-04 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league_manager', '0026_auto_20161104_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerreport',
            name='is_wounded',
        ),
        migrations.AlterField(
            model_name='playerupgrade',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upgrade', to='league_manager.Ref_Skills'),
        ),
    ]
