# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-05 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_manager', '0027_auto_20161104_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Ag',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='Ar',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='F',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='M',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='skills',
            field=models.ManyToManyField(null=True, to='league_manager.Ref_Skills'),
        ),
    ]
