# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-06 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_manager', '0030_player_niggling_injuries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='skills',
            field=models.ManyToManyField(null=True, related_name='player', to='league_manager.Ref_Skills'),
        ),
    ]
